# Generated by Django 5.1.1 on 2024-10-11 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created'], name='post_post_created_22b748_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='post_post_user_id_57d352_idx'),
        ),
    ]
