# Generated by Django 5.1.1 on 2024-10-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0003_attributekey_key_name_attributevalue_value_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title'], name='olcha_categ_title_c5b36a_idx'),
        ),
    ]
